{
 "title": "年度比較",
 "tags": [ "sales" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "今年訂單量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nFROM transaction\r\nWHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE)\r\nAND transaction_at < DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year';\r\n"
    }
   ]
  },
  {
   "title": "訂單量月趨勢",
   "type": "trend",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    last_year.month,\r\n    this_year.transaction_count AS this_year_count,\r\n    last_year.transaction_count AS last_year_count\r\n\r\nFROM \r\n    (SELECT \r\n        EXTRACT(MONTH FROM transaction_at) AS month,\r\n        COUNT(*) AS transaction_count\r\n    FROM transaction\r\n    WHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\n      AND transaction_at < DATE_TRUNC('year', CURRENT_DATE)\r\n    GROUP BY month) AS last_year\r\n\r\nLEFT JOIN \r\n    (SELECT \r\n        EXTRACT(MONTH FROM transaction_at) AS month,\r\n        COUNT(*) AS transaction_count\r\n    FROM transaction\r\n    WHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE)\r\n      AND transaction_at < DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year'\r\n    GROUP BY month) AS this_year\r\n\r\nON last_year.month = this_year.month\r\nORDER BY last_year.month;"
    }
   ]
  },
  {
   "title": "今年平均客單價",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(total) / COUNT(*) AS avg_order_value\r\nFROM transaction\r\nWHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE)\r\nAND transaction_at < DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year';"
    }
   ]
  },
  {
   "title": "客單價月趨勢",
   "type": "trend",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    last_year.month,\r\n    this_year.avg_order_value AS this_year_avg_value,\r\n    last_year.avg_order_value AS last_year_avg_value\r\n\r\nFROM \r\n    (SELECT \r\n        EXTRACT(MONTH FROM transaction_at) AS month,\r\n        SUM(total) / COUNT(*) AS avg_order_value\r\n    FROM transaction\r\n    WHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\n      AND transaction_at < DATE_TRUNC('year', CURRENT_DATE)\r\n    GROUP BY month) AS last_year\r\n\r\nLEFT JOIN \r\n    (SELECT \r\n        EXTRACT(MONTH FROM transaction_at) AS month,\r\n        SUM(total) / COUNT(*) AS avg_order_value\r\n    FROM transaction\r\n    WHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE)\r\n      AND transaction_at < DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year'\r\n    GROUP BY month) AS this_year\r\n\r\nON last_year.month = this_year.month\r\nORDER BY last_year.month;"
    }
   ]
  },
  {
   "title": "去年訂單量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nFROM transaction\r\nWHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\nAND transaction_at < DATE_TRUNC('year', CURRENT_DATE);"
    }
   ]
  },
  {
   "title": "去年平均客單價",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(total) / COUNT(*) AS avg_order_value\r\nFROM transaction\r\nWHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\nAND transaction_at < DATE_TRUNC('year', CURRENT_DATE);"
    }
   ]
  },
  {
   "title": "各通路轉換次數",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COALESCE(this_year.referrer, last_year.referrer) AS referrer,\r\n    this_year.transaction_count AS this_year_count,\r\n    last_year.transaction_count AS last_year_count,\r\n    ROUND(this_year.transaction_count * 100.0 / SUM(this_year.transaction_count) OVER(), 2) AS this_year_percentage,\r\n    ROUND(last_year.transaction_count * 100.0 / SUM(last_year.transaction_count) OVER(), 2) AS last_year_percentage\r\nFROM \r\n    (SELECT \r\n        -- referrer,\r\n        CASE \r\n            WHEN referrer = 'direct' THEN '直接訪問'\r\n            WHEN referrer = 'email' THEN '電子郵件'\r\n            WHEN referrer = 'paid_ads' THEN '廣告'\r\n            WHEN referrer = 'referral' THEN '其他網站'\r\n            WHEN referrer = 'search_engine' THEN '搜尋引擎'\r\n            WHEN referrer = 'social_media' THEN '社群網站'\r\n            WHEN referrer = 'unknown' THEN '未知'\r\n        END AS referrer,\r\n        COUNT(*) AS transaction_count\r\n    FROM customer_behavior\r\n    WHERE action_type = 'purchase'\r\n      AND action_at >= DATE_TRUNC('year', CURRENT_DATE)\r\n      AND action_at < DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year'\r\n    GROUP BY referrer) AS this_year\r\n\r\nFULL JOIN \r\n    (SELECT \r\n        -- referrer,\r\n        CASE \r\n            WHEN referrer = 'direct' THEN '直接訪問'\r\n            WHEN referrer = 'email' THEN '電子郵件'\r\n            WHEN referrer = 'paid_ads' THEN '廣告'\r\n            WHEN referrer = 'referral' THEN '其他網站'\r\n            WHEN referrer = 'search_engine' THEN '搜尋引擎'\r\n            WHEN referrer = 'social_media' THEN '社群網站'\r\n            WHEN referrer = 'unknown' THEN '未知'\r\n        END AS referrer,\r\n        COUNT(*) AS transaction_count\r\n    FROM customer_behavior\r\n    WHERE action_type = 'purchase'\r\n      AND action_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\n      AND action_at < DATE_TRUNC('year', CURRENT_DATE)\r\n    GROUP BY referrer) AS last_year\r\n\r\nON this_year.referrer = last_year.referrer\r\nORDER BY this_year_count DESC;"
    }
   ]
  },
  {
   "title": "各類商品購買次數",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COALESCE(this_year.category, last_year.category) AS category,\r\n    this_year.transaction_count AS this_year_count,\r\n    last_year.transaction_count AS last_year_count,\r\n    ROUND(this_year.transaction_count * 100.0 / SUM(this_year.transaction_count) OVER(), 2) AS this_year_percentage,\r\n    ROUND(last_year.transaction_count * 100.0 / SUM(last_year.transaction_count) OVER(), 2) AS last_year_percentage\r\nFROM \r\n    (SELECT \r\n        p.category,\r\n        COUNT(*) AS transaction_count\r\n    FROM transaction t\r\n    JOIN product p ON t.product_id = p.product_id \r\n    WHERE t.transaction_at >= DATE_TRUNC('year', CURRENT_DATE)\r\n    AND t.transaction_at < DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year'\r\n    GROUP BY p.category) AS this_year\r\n\r\nFULL JOIN \r\n    (SELECT \r\n        p.category,\r\n        COUNT(*) AS transaction_count\r\n    FROM transaction t\r\n    JOIN product p ON t.product_id = p.product_id \r\n    WHERE t.transaction_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\n    AND t.transaction_at < DATE_TRUNC('year', CURRENT_DATE)\r\n    GROUP BY p.category) AS last_year\r\n\r\nON this_year.category = last_year.category\r\nORDER BY this_year_count DESC;"
    }
   ]
  },
  {
   "title": "各類商品購買金額",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COALESCE(this_year.category, last_year.category) AS category,\r\n    this_year.transaction_total AS this_year_total,\r\n    last_year.transaction_total AS last_year_total,\r\n    ROUND(this_year.transaction_total * 100.0 / SUM(this_year.transaction_total) OVER(), 2) AS this_year_percentage,\r\n    ROUND(last_year.transaction_total * 100.0 / SUM(last_year.transaction_total) OVER(), 2) AS last_year_percentage\r\nFROM \r\n    (SELECT \r\n        p.category,\r\n        SUM(total) AS transaction_total\r\n    FROM transaction t\r\n    JOIN product p ON t.product_id = p.product_id  \r\n    WHERE t.transaction_at >= DATE_TRUNC('year', CURRENT_DATE)\r\n    AND t.transaction_at < DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year'\r\n    GROUP BY p.category) AS this_year\r\n\r\nFULL JOIN \r\n    (SELECT\r\n        p.category,\r\n        SUM(total) AS transaction_total\r\n    FROM transaction t\r\n    JOIN product p ON t.product_id = p.product_id \r\n    WHERE t.transaction_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\n    AND t.transaction_at < DATE_TRUNC('year', CURRENT_DATE)\r\n    GROUP BY p.category) AS last_year\r\n\r\nON this_year.category = last_year.category\r\nORDER BY this_year_total DESC;"
    }
   ]
  }
 ]
}