{
 "title": "整體會員樣態",
 "tags": [ "sales" ],
 "time": { "from": "2023-12-31T16:00:00.000Z", "to": "2025-02-28T16:00:00.000Z" },
 "panels": [
  {
   "title": "註冊會員數",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT customer_id)\r\nFROM customer;"
    }
   ]
  },
  {
   "title": "新註冊會員數月趨勢",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('month', registered_at) AS month,\r\n    COUNT(DISTINCT customer_id) AS customer_count\r\nFROM customer\r\nWHERE registered_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\nGROUP BY month\r\nORDER BY month;"
    }
   ]
  },
  {
   "title": "購買會員數月趨勢",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('month', transaction_at) AS month,\r\n    COUNT(DISTINCT customer_id) AS customer_count\r\nFROM transaction\r\nWHERE transaction_at >= DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year'\r\nGROUP BY month\r\nORDER BY month;"
    }
   ]
  },
  {
   "title": "曾購買會員數",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT customer_id)\r\nFROM transaction;\r\n"
    }
   ]
  },
  {
   "title": "會員性別比例",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    gender, \r\n    COUNT(DISTINCT customer_id) AS customer_count\r\nFROM customer\r\nGROUP BY gender;"
    }
   ]
  },
  {
   "title": "會員年齡比例",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    -- COUNT(DISTINCT customer_id) AS customer_count,\r\n    ROUND(COUNT(DISTINCT customer_id) * 100.0 / SUM(COUNT(DISTINCT customer_id)) OVER(), 2) AS customer_percentage,\r\n    CASE \r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) < 20 THEN '0-19歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 20 AND 29 THEN '20-29歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 30 AND 39 THEN '30-39歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 40 AND 49 THEN '40-49歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 50 AND 59 THEN '50-59歲'\r\n        ELSE '60歲以上'\r\n    END AS age_group\r\n    \r\nFROM customer\r\nGROUP BY age_group;"
    }
   ]
  },
  {
   "title": "通路轉換比例",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nCASE \r\n    WHEN referrer = 'direct' THEN '直接訪問'\r\n    WHEN referrer = 'email' THEN '電子郵件'\r\n    WHEN referrer = 'paid_ads' THEN '廣告'\r\n    WHEN referrer = 'referral' THEN '其他網站'\r\n    WHEN referrer = 'search_engine' THEN '搜尋引擎'\r\n    WHEN referrer = 'social_media' THEN '社群網站'\r\n    WHEN referrer = 'unknown' THEN '未知'\r\nEND AS referrer,\r\n-- COUNT(*),\r\nROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS referrer_percentage\r\nFROM customer_behavior\r\nWHERE action_type = 'purchase'\r\nGROUP BY referrer\r\nORDER BY referrer_percentage DESC;"
    }
   ]
  },
  {
   "title": "各類商品購買次數比例",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT p.category,\r\n-- COUNT(t.*),\r\nROUND(COUNT(t.*) * 100.0 / SUM(COUNT(t.*)) OVER(), 2) AS category_percentage\r\nFROM transaction t\r\nLEFT JOIN product p\r\nON t.product_id=p.product_id\r\nGROUP BY p.category\r\nORDER BY category_percentage DESC;"
    }
   ]
  },
  {
   "title": "各類商品購買金額比例",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT p.category,\r\n-- SUM(t.total),\r\nROUND(SUM(t.total) * 100.0 / SUM(SUM(t.total)) OVER(), 2) AS category_percentage\r\nFROM transaction t\r\nLEFT JOIN product p\r\nON t.product_id=p.product_id\r\nGROUP BY p.category\r\nORDER BY category_percentage DESC;"
    }
   ]
  },
  {
   "title": "會員資料更新日期",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT registered_at FROM customer ORDER BY registered_at desc LIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "交易資料更新日期",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT action_at FROM customer_behavior WHERE action_type='view' ORDER BY action_at desc LIMIT 1;\r\n"
    }
   ]
  }
 ]
}