{
 "title": "本周比較",
 "tags": [ "sales" ],
 "time": { "from": "2025-03-23T18:28:14.344Z", "to": "2025-03-24T18:28:14.344Z" },
 "templating": {
  "list": [
   {
    "name": "gender",
    "label": "性別",
    "query": "SELECT \nCASE \n WHEN gender = 'F' THEN '女'\n WHEN gender = 'M' THEN '男'\nEND AS gender\nFROM customer;"
   },
   {
    "name": "age_group",
    "label": "年齡級距",
    "query": "SELECT \n    CASE \n        WHEN DATE_PART('year', AGE(NOW(), birth)) < 20 THEN '0-19歲'\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 20 AND 29 THEN '20-29歲'\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 30 AND 39 THEN '30-39歲'\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 40 AND 49 THEN '40-49歲'\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 50 AND 59 THEN '50-59歲'\n        ELSE '60歲以上'\n    END AS age_group\nFROM customer\nGROUP BY age_group\nORDER BY age_group;\n"
   },
   {
    "name": "referrer",
    "label": "通路",
    "query": "SELECT \nCASE \n WHEN referrer = 'direct' THEN '直接訪問'\n WHEN referrer = 'email' THEN '電子郵件'\n WHEN referrer = 'paid_ads' THEN '廣告'\n WHEN referrer = 'referral' THEN '其他網站'\n WHEN referrer = 'search_engine' THEN '搜尋引擎'\n WHEN referrer = 'social_media' THEN '社群網站'\n WHEN referrer = 'unknown' THEN '未知'\nEND AS referrer\nFROM customer_behavior;"
   }
  ]
 },
 "panels": [
  {
   "title": "本周訂單數",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'last week' AS period,\r\n    COUNT(*) AS count\r\nFROM customer_behavior b\r\nJOIN customer c ON b.customer_id=c.customer_id\r\nWHERE b.action_type = 'purchase'\r\nAND \r\n    (\r\n    (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n    )\r\nAND \r\n    (\r\n    (c.gender = 'F' AND '女' IN (${gender}))\r\n    OR (c.gender = 'M' AND '男' IN (${gender}))\r\n    )\r\nAND\r\n    (\r\n    (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n    OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n    OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n    OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n    OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n    OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n    OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n    )\r\nAND b.action_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '2 week'\r\nAND b.action_at < DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\n\r\nUNION ALL\r\n\r\nSELECT \r\n    'this week' AS period,\r\n    COUNT(*) AS count\r\nFROM customer_behavior b\r\nJOIN customer c ON b.customer_id=c.customer_id\r\nWHERE b.action_type = 'purchase'\r\nAND \r\n    (\r\n    (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n    )\r\nAND \r\n    (\r\n    (c.gender = 'F' AND '女' IN (${gender}))\r\n    OR (c.gender = 'M' AND '男' IN (${gender}))\r\n    )\r\nAND\r\n    (\r\n    (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n    OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n    OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n    OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n    OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n    OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n    OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n    )\r\nAND b.action_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\nAND b.action_at < DATE_TRUNC('week', CURRENT_DATE)\r\nORDER BY period ASC;"
    }
   ]
  },
  {
   "title": "購買會員年齡",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ROUND(COUNT(DISTINCT b.customer_id) * 100.0 / SUM(COUNT(DISTINCT b.customer_id)) OVER(), 2) AS percentage,\r\n    CASE \r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) < 20 THEN '0-19歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 20 AND 29 THEN '20-29歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 30 AND 39 THEN '30-39歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 40 AND 49 THEN '40-49歲'\r\n        WHEN DATE_PART('year', AGE(NOW(), birth)) BETWEEN 50 AND 59 THEN '50-59歲'\r\n        ELSE '60歲以上'\r\n    END AS age_group\r\nFROM customer_behavior b\r\nJOIN customer c ON b.customer_id = c.customer_id\r\nWHERE b.action_type = 'purchase'\r\nAND\r\n    (\r\n    (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n    )\r\nAND \r\n    (\r\n    (c.gender = 'F' AND '女' IN (${gender}))\r\n    OR (c.gender = 'M' AND '男' IN (${gender}))\r\n    )\r\nAND\r\n    (\r\n    (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n    OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n    OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n    OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n    OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n    OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n    OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n    )\r\nAND b.action_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\nAND b.action_at < DATE_TRUNC('week', CURRENT_DATE)\r\nGROUP BY age_group\r\nORDER BY age_group;"
    }
   ]
  },
  {
   "title": "購買通路",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN b.referrer = 'direct' THEN '直接訪問'\r\n        WHEN b.referrer = 'email' THEN '電子郵件'\r\n        WHEN b.referrer = 'paid_ads' THEN '廣告'\r\n        WHEN b.referrer = 'referral' THEN '其他網站'\r\n        WHEN b.referrer = 'search_engine' THEN '搜尋引擎'\r\n        WHEN b.referrer = 'social_media' THEN '社群網站'\r\n        WHEN b.referrer = 'unknown' THEN '未知'\r\n    END AS referrer, \r\n    -- COUNT(*) AS customer_count,\r\n    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS percentage\r\nFROM customer_behavior b\r\nJOIN customer c ON b.customer_id = c.customer_id\r\nWHERE b.action_type = 'purchase'\r\nAND \r\n    (\r\n    (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n    )\r\nAND \r\n    (\r\n    (c.gender = 'F' AND '女' IN (${gender}))\r\n    OR (c.gender = 'M' AND '男' IN (${gender}))\r\n    )\r\nAND\r\n    (\r\n    (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n    OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n    OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n    OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n    OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n    OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n    OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n    )\r\nAND b.action_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\nAND b.action_at < DATE_TRUNC('week', CURRENT_DATE)\r\nGROUP BY b.referrer\r\nORDER BY percentage DESC ;"
    }
   ]
  },
  {
   "title": "會員購物歷程",
   "type": "mckn-funnel-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    b.action_type,\r\n    COUNT(b.customer_id) AS customer_count\r\nFROM customer_behavior b\r\nJOIN customer c ON b.customer_id = c.customer_id\r\nWHERE \r\n    (\r\n    (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n    )\r\nAND \r\n    (\r\n    (c.gender = 'F' AND '女' IN (${gender}))\r\n    OR (c.gender = 'M' AND '男' IN (${gender}))\r\n    )\r\nAND\r\n    (\r\n    (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n    OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n    OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n    OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n    OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n    OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n    OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n    )\r\nAND b.action_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\nAND b.action_at < DATE_TRUNC('week', CURRENT_DATE)\r\nGROUP BY b.action_type\r\nORDER BY customer_count desc;"
    }
   ]
  },
  {
   "title": "購買會員性別",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    c.gender,\r\n    COUNT(DISTINCT b.customer_id) AS customer_count\r\nFROM customer_behavior b\r\nJOIN customer c ON b.customer_id=c.customer_id\r\nWHERE b.action_type = 'purchase'\r\nAND\r\n    (\r\n    (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n    OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n    )\r\nAND \r\n    (\r\n    (c.gender = 'F' AND '女' IN (${gender}))\r\n    OR (c.gender = 'M' AND '男' IN (${gender}))\r\n    )\r\nAND\r\n    (\r\n    (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n    OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n    OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n    OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n    OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n    OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n    OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n    )\r\nAND b.action_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\nAND b.action_at < DATE_TRUNC('week', CURRENT_DATE)\r\nGROUP BY c.gender;"
    }
   ]
  },
  {
   "title": "各類商品購買情形",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COALESCE(this_week.category, last_week.category) AS category,\r\n    this_week.transaction_count AS this_week_count,\r\n    last_week.transaction_count AS last_week_count,\r\n    this_week.transaction_total AS this_week_total,\r\n    last_week.transaction_total AS last_week_total\r\nFROM \r\n    (SELECT \r\n        p.category AS category,\r\n        COUNT(*) AS transaction_count,\r\n        SUM(total) AS transaction_total\r\n    FROM transaction t\r\n    JOIN product p ON t.product_id = p.product_id\r\n    JOIN customer c ON t.customer_id = c.customer_id\r\n    JOIN customer_behavior b ON t.customer_id = b.customer_id\r\n    AND t.product_id = b.product_id\r\n    AND t.transaction_at = b.action_at\r\n    WHERE \r\n        (\r\n        (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n        )\r\n    AND \r\n        (\r\n        (c.gender = 'F' AND '女' IN (${gender}))\r\n        OR (c.gender = 'M' AND '男' IN (${gender}))\r\n        )\r\n    AND\r\n        (\r\n        (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n        OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n        OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n        OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n        OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n        OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n        OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n        )\r\n    AND t.transaction_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\n    AND t.transaction_at < DATE_TRUNC('week', CURRENT_DATE)\r\n    GROUP BY p.category) AS this_week\r\n\r\nFULL JOIN \r\n    (SELECT \r\n        p.category AS category,\r\n        COUNT(*) AS transaction_count,\r\n        SUM(total) AS transaction_total\r\n    FROM transaction t\r\n    JOIN product p ON t.product_id = p.product_id\r\n    JOIN customer c ON t.customer_id = c.customer_id\r\n    JOIN customer_behavior b ON t.customer_id = b.customer_id\r\n    AND t.product_id = b.product_id\r\n    AND t.transaction_at = b.action_at\r\n    WHERE \r\n        (\r\n        (DATE_PART('year', AGE(NOW(), c.birth)) < 20 AND '0-19歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 20 AND 29 AND '20-29歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 30 AND 39 AND '30-39歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 40 AND 49 AND '40-49歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) BETWEEN 50 AND 59 AND '50-59歲' IN (${age_group}))\r\n        OR (DATE_PART('year', AGE(NOW(), c.birth)) >= 60 AND '60歲以上' IN (${age_group}))\r\n        )\r\n    AND \r\n        (\r\n        (c.gender = 'F' AND '女' IN (${gender}))\r\n        OR (c.gender = 'M' AND '男' IN (${gender}))\r\n        )\r\n    AND\r\n        (\r\n        (b.referrer = 'direct' AND '直接訪問' IN (${referrer})) \r\n        OR (b.referrer = 'email' AND '電子郵件' IN (${referrer})) \r\n        OR (b.referrer = 'paid_ads' AND '廣告' IN (${referrer})) \r\n        OR (b.referrer = 'referral' AND '其他網站' IN (${referrer})) \r\n        OR (b.referrer = 'search_engine' AND '搜尋引擎' IN (${referrer})) \r\n        OR (b.referrer = 'social_media' AND '社群網站' IN (${referrer})) \r\n        OR (b.referrer = 'unknown' AND '未知' IN (${referrer})) \r\n        )\r\n    AND t.transaction_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '2 week'\r\n    AND t.transaction_at < DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\n    GROUP BY p.category) AS last_week\r\n\r\nON this_week.category = last_week.category\r\nORDER BY this_week.category;"
    }
   ]
  },
  {
   "title": "本周促銷活動",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM promotion\r\nWHERE published_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'\r\nAND published_at < DATE_TRUNC('week', CURRENT_DATE)"
    }
   ]
  },
  {
   "title": "上周促銷活動",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM promotion\r\nWHERE published_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '2 week'\r\nAND published_at < DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '1 week'"
    }
   ]
  }
 ]
}